version: "3.9"

services:
  backend:
    build:
      context: ./backend
    environment:
      NODE_ENV: production
    command: npm run start:prod
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    environment:
      NODE_ENV: production
    command: npm run start
    ports:
      - "8080:8080"

  db:
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: toor
