version: "3.9"

services:
  backend:
    build:
      context: ./backend
      target: production
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      target: production
    environment:
      NODE_ENV: production
    ports:
      - "8080:80"

  db:
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: toor
