version: "3.9"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/app/src
    command: npm run start:dev

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      args:
        - NODE_ENV=development
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    command: npm run dev

  db:
    container_name: db
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: toor
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pgdata:
